// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeSecretKey(arg1) {
  return window['go']['app']['App']['ChangeSecretKey'](arg1);
}

export function ClearClipboard() {
  return window['go']['app']['App']['ClearClipboard']();
}

export function CopyNoteToClipboard(arg1, arg2) {
  return window['go']['app']['App']['CopyNoteToClipboard'](arg1, arg2);
}

export function CreateNote(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateNote'](arg1, arg2, arg3, arg4);
}

export function DeleteNote(arg1) {
  return window['go']['app']['App']['DeleteNote'](arg1);
}

export function EditNote(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['EditNote'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportBackup(arg1) {
  return window['go']['app']['App']['ExportBackup'](arg1);
}

export function ExportConfig(arg1) {
  return window['go']['app']['App']['ExportConfig'](arg1);
}

export function GetMaskedSecretKey() {
  return window['go']['app']['App']['GetMaskedSecretKey']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function ImportConfig(arg1) {
  return window['go']['app']['App']['ImportConfig'](arg1);
}

export function IsSecretKeyConfigured() {
  return window['go']['app']['App']['IsSecretKeyConfigured']();
}

export function ListNotes(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ListNotes'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenFileDialog() {
  return window['go']['app']['App']['OpenFileDialog']();
}

export function OpenNote(arg1, arg2) {
  return window['go']['app']['App']['OpenNote'](arg1, arg2);
}

export function PreviewRestore(arg1) {
  return window['go']['app']['App']['PreviewRestore'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['app']['App']['RestoreBackup'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['app']['App']['SaveFileDialog'](arg1);
}

export function SetClipboardText(arg1) {
  return window['go']['app']['App']['SetClipboardText'](arg1);
}

export function SetFavorite(arg1, arg2) {
  return window['go']['app']['App']['SetFavorite'](arg1, arg2);
}

export function SetPinned(arg1, arg2) {
  return window['go']['app']['App']['SetPinned'](arg1, arg2);
}

export function SetupSecretKey(arg1) {
  return window['go']['app']['App']['SetupSecretKey'](arg1);
}

export function UpdateClipboardTimeout(arg1) {
  return window['go']['app']['App']['UpdateClipboardTimeout'](arg1);
}

export function UpdateTheme(arg1) {
  return window['go']['app']['App']['UpdateTheme'](arg1);
}
