// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {app} from '../models';
import {service} from '../models';

export function ChangeSecretKey(arg1:string):Promise<void>;

export function ClearClipboard():Promise<void>;

export function CopyNoteToClipboard(arg1:string,arg2:string):Promise<void>;

export function CreateNote(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<domain.NoteCard>;

export function DeleteNote(arg1:string):Promise<void>;

export function EditNote(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<domain.NoteCard>;

export function ExportBackup(arg1:string):Promise<domain.BackupFile>;

export function ExportConfig(arg1:string):Promise<void>;

export function GetMaskedSecretKey():Promise<string>;

export function GetSettings():Promise<domain.Settings>;

export function ImportConfig(arg1:string):Promise<void>;

export function IsSecretKeyConfigured():Promise<boolean>;

export function ListNotes(arg1:string,arg2:string,arg3:number,arg4:number,arg5:boolean):Promise<app.ListNotesResult>;

export function OpenFileDialog():Promise<string>;

export function OpenNote(arg1:string,arg2:string):Promise<domain.DecryptedNote>;

export function PreviewRestore(arg1:string):Promise<service.RestorePreview>;

export function RestoreBackup(arg1:string,arg2:Array<string>):Promise<number>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SetClipboardText(arg1:string):Promise<void>;

export function SetFavorite(arg1:string,arg2:boolean):Promise<void>;

export function SetPinned(arg1:string,arg2:boolean):Promise<void>;

export function SetupSecretKey(arg1:string):Promise<void>;

export function UpdateClipboardTimeout(arg1:number):Promise<void>;

export function UpdateTheme(arg1:string):Promise<void>;
